# Generated by Django 5.1.4 on 2024-12-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdPatient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_comment='first name or last name for ppl from other country.', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, db_comment='first name or last name for ppl from other country.', max_length=30, null=True)),
                ('patient_system_id', models.CharField(db_comment='e.g. SAP ID', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'cd_patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabRecord',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lab_record_id', models.CharField(max_length=100, unique=True)),
                ('appointment_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lab_record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('result_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('spec_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('spec_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'lab_results',
                'managed': False,
            },
        ),
    ]
